version: 2.1

jobs:
  build:
    docker:
      - image: gcc:7.4

    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y cmake check
      - run:
          name: Prepare build directory
          command: |
            mkdir build 
            cd build 
            cmake .. 
      - run:
          name: Build
          command: |
            cd build 
            make
      - run:
          name: test
          command: |
            cd build 
            make test
