version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apt-get update
            DEBIAN_FRONTEND="noninteractive" apt-get install -y cmake check tzdata
      - run:
          name: Prepare build directory
          command: |
            mkdir build 
            cd build 
            cmake .. 
      - run:
          name: Build
          command: |
            cd build 
            make
      - run:
          name: test
          command: |
            cd build 
            make test
